### ISSUE TITLE
Cannot load module mod_authnz_ibmdb2 for Apache 2.2.32

### ISSUE THREAD

**Issue by mohan1809** [tessus/mod_authnz_ibmdb2#1]
I am seeing this exception with Apache 2.2.32.The Load Module fails to load mod_authnz_ibmdb2.so

httpd: Syntax error on line 287 of /etc/httpd/conf/httpd.conf: Syntax error on line 5 of /etc/httpd/conf.d/ssl.conf: Cannot load /etc/httpd/modules/mod_authnz_ibmdb2.so into server: /etc/httpd/modules/mod_authnz_ibmdb2.so: undefined symbol: write_cache

Apache version
Server version: Apache/2.2.32 (Unix)
Server built:   Mar 27 2017 15:48:19

Can any one help on the above issue.

**Comment by tessus** [comment]
Can you please be a bit more specific? Which OS? Which version of mod_authnz_ibmdb2?

I'm using the module myself and I also checked the symbol table of the shared object. write_cache is a global exported symbol. You can see the symbol table on Linux with:

```
readelf --syms ./mod_authnz_ibmdb2.so
```
How did you compile the module?

I'm sorry, I've never seen this error before, but if you have a dev/test machine I can ssh into, I can have a look. Anyway, I'm out for today. It's almost 3 in the morning and  I need some sleep.

**Comment by mohan1809** [comment]
[root@10 modules]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

mod_authnz version

mod_authnz_ibmdb2-2.2.5


Command Results
------------------
readelf --syms ./mod_authnz_ibmdb2.so

   110: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SQLAllocHandle
   111: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND apr_md5_final
   112: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND strcmp@@GLIBC_2.2.5
   113: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND ap_add_version_component
   114: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND ap_log_error
   115: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND strcpy@@GLIBC_2.2.5
   116: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND write_group_cache
   117: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND apr_pstrdup
   118: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SQLGetConnectAttr
   119: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND read_cache
   120: 0000000000207258     0 NOTYPE  GLOBAL DEFAULT   24 _end
   121: 0000000000002d10   271 FUNC    GLOBAL DEFAULT   11 ibmdb2_disconnect
   122: 00000000002071e0   104 OBJECT  GLOBAL DEFAULT   23 authnz_ibmdb2_module
   123: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SQLGetData
   124: 0000000000002b50   290 FUNC    GLOBAL DEFAULT   11 get_stmt_err
   125: 0000000000207248     0 NOTYPE  GLOBAL DEFAULT   23 _edata
   126: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND ap_log_rerror
   127: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SQLDriverConnect
   128: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND apr_password_validate
   129: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND ap_set_int_slot
   130: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND SQLDisconnect
   131: 0000000000001b08     0 FUNC    GLOBAL DEFAULT    9 _init
[root@10 modules]#

The module compiled as below 

cd /usr/ironhide/webserver/db2/mod_authnz_ibmdb2; cp /tmp/tmp-webserver/makemod .; dos2unix makemod; chmod +x makemod; ./makemod

**Comment by mohan1809** [comment]
forgot to attach the file.Attaching here complete output

[mod_authnz_ibmdb2.txt](https://github.com/tessus/mod_authnz_ibmdb2/files/878914/mod_authnz_ibmdb2.txt)

**Comment by tessus** [comment]
As you can see in the output `write_cache` is in the symbol table.

```
Symbol table '.dynsym' contains 72 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     5: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND write_cache
Symbol table '.symtab' contains 132 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
    66: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND write_cache
```

I believe there's something off with your config files. The module should be loaded **after** all other httpd's internal modules and before any other directives.

What is line 287 in your `/etc/httpd/conf/httpd.conf` and what is line 5 in your `/etc/httpd/conf.d/ssl.conf`?

**Comment by mohan1809** [comment]
On 287 line i see that including the /conf/*.conf files

and in ssl.conf at line number 5 
LoadModule <moduleName> modules/mod_authnz_ibmdb2.so

it is loading the ssl.conf in httpd.conf at line 287.

**Comment by tessus** [comment]
The line has to look like this:

```
LoadModule authnz_ibmdb2_module modules/mod_authnz_ibmdb2.so
```

**Comment by tessus** [comment]
Also, add the module in `httpd.conf` in the section (**after** all other modules):

```
#
# Dynamic Shared Object (DSO) Support
#
```

This should be around line 90-100.

**Comment by mohan1809** [comment]
Yes.The above is correct

One question
Will it resolve this loading issue if i add in httpd.conf? and why this is causing if i include the same from the ssl.conf.

**Comment by mohan1809** [comment]
I am using lie this in ssl.conf

<% if (useDB2) { %>
LoadModule authnz_ibmdb2_module modules/mod_authnz_ibmdb2.so
<% } else { %>
LoadModule mysql_auth_module modules/mod_auth_mysql.so
<% } %>

This is causing the issue and if i add mod_authnz_ibmdb2.so in httpd.conf will that sufficient

**Comment by tessus** [comment]
What do you mean by 'the above is correct'?

Did you change the line to `LoadModule authnz_ibmdb2_module modules/mod_authnz_ibmdb2.so`? Does it work now?

>Will it resolve this loading issue if i add in httpd.conf? and why this is causing if i include the same from the ssl.conf.

Apache modules should be be loaded at the beginning of the configuration file, otherwise you can run into dependency issues. The order of the modules is important as well.
Let's say functions from module A are needed in module B. This means you have to load module A first.

**Comment by tessus** [comment]
This code looks like a chef cookbook. I suggest you get it working first, before you start writing a cookbook.

As I mentioned before, I have never seen this error before. The error message might be wrong due to some side effect. I can't say for sure, since I don't have access to your system.

Try the following:

- remove the `if` `else` blocks in ssl.conf
   - load only mysql_auth_module (does this work?)
   - load only authnz_ibmdb2_module  (does this work?)
- put authnz_ibmdb2_module in httpd.conf (does this work?)

**Comment by mohan1809** [comment]
Ok.My question is if i add that module in httpd.conf instead of ssl.conf will that work(Remove from ssl.conf).

I cannot verify this immediatly.I have automated process and during the process it will install the Apache server along with other dependency softwares.it will take some time to me to verify

**Comment by tessus** [comment]
Sorry, I can't answer that, because the error message you are seeing does not make any sense.

You have to get access to a test machine and run some tests. I can tell you how I set it up and that it works on my server that way:

I put the `LoadModule` directive in httpd.conf after all other httpd's modules. That's it.

**Comment by mohan1809** [comment]
I have added manually to verify if it works this way or not.Can you please  provide me the command to verify the LoadModule on that Machine.

**Comment by tessus** [comment]
I don't understand. What verify command?

Start the httpd server. If you don't get any errors, it's been loaded. Or you can see it in the Server Signature.

Or you can run `./httpd -M`
If you can see ` authnz_ibmdb2_module (shared)` somewhere at the end, all is good.

**Comment by tessus** [comment]
Any news?

**Comment by mohan1809** [comment]
I still see the same issue.If possible can you login to this machine and see if there is any issue in starting the apache

[root@10 httpd-2.4.25]# apachectl -DSkipApreq -k restart
httpd: Syntax error on line 284 of /etc/httpd/conf/httpd.conf: Cannot load /etc/httpd/modules/mod_authnz_ibmdb2.so into server: /etc/httpd/modules/mod_authnz_ibmdb2.so: undefined symbol: write_cache
[root@10 httpd-2.4.25]#

Ip :169.44.183.109

Thanks
Mohan

**Comment by mohan1809** [comment]
I have tried with the Apache 2.4.25 as well

**Comment by mohan1809** [comment]
[root@10 httpd-2.4.25]# ./httpd -version
Server version: Apache/2.4.25 (Unix)
Server built:   Apr  1 2017 05:45:34
[root@10 httpd-2.4.25]# ./httpd -M
httpd: Syntax error on line 149 of /etc/httpd/httpd.conf: Cannot load modules/mod_auth_basic.so into server: /etc/httpd/modules/mod_auth_basic.so: undefined symbol: ap_log_rerror

**Comment by tessus** [comment]
Just came home and I'm really tired. Please send me an email with the user/pwd for the machine. You can find my email address in my github profile. If you want to encrypt the email, my gpg key id is 0xC11F128D

>httpd: Syntax error on line 149 of /etc/httpd/httpd.conf: Cannot load modules/mod_auth_basic.so into server: /etc/httpd/modules/mod_auth_basic.so: undefined symbol: ap_log_rerror

This error message tells me that the problem is not with my module. Something is off with the apache config.

No worries, we'll figure it out. I'll have a look at it this afternoon around 14:00 EST.

**Comment by tessus** [comment]
OP can't give me access to the machine.

This is clearly an Apache configuration issue and has nothing to do with the module itself.
